/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../src/App.vue')['default']
    Exception: typeof import('./../src/components/Exception/index.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IconLocalNotFound: typeof import('~icons/local/not-found')['default']
    Login: typeof import('./../src/views/base/login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('@/components/Exception/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
  }
}
