/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BasicLayout from "@/layout/basic-layout/index.vue";
import BlankLayout from "@/layout/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  basic: BasicLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  comp_loading: () => import("@/views/comp/loading/index.vue"),
  comp_table_basic: () => import("@/views/comp/table/basic/index.vue"),
  "comp_table_use-table": () => import("@/views/comp/table/use-table/index.vue"),
  dashboard_analysis: () => import("@/views/dashboard/analysis/index.vue"),
  dashboard_workbench: () => import("@/views/dashboard/workbench/index.vue"),
  document_vue3: () => import("@/views/document/vue3/index.vue"),
  "func_error-log": () => import("@/views/func/error-log/index.vue"),
  func_sub1: () => import("@/views/func/sub1/index.vue"),
  "func_upload-chunk": () => import("@/views/func/upload-chunk/index.vue"),
  "permission_front_auth-page-a": () => import("@/views/permission/front/auth-page-a/index.vue"),
  "permission_front_auth-page-b": () => import("@/views/permission/front/auth-page-b/index.vue"),
  permission_front_btn: () => import("@/views/permission/front/btn/index.vue"),
  plugin_charts_echarts: () => import("@/views/plugin/charts/echarts/index.vue"),
  redirect: () => import("@/views/redirect/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
