# 工作流名称：Release Drafter（自动生成发布草稿）
name: Release Drafter

# 触发条件：当代码推送到 master 分支时触发
on:
  push:
    branches:
      - master

# 权限设置：工作流运行时的权限范围
permissions:
  contents: read # 允许读取仓库内容
  pull-requests: write # 允许操作 PR（如添加标签，用于分类变更）

jobs:
  # 任务：更新发布草稿
  update_release_draft:
    # 任务所需权限（覆盖全局权限）
    permissions:
      contents: write # 允许创建 GitHub Release（必须有写入权限）
      pull-requests: write # 允许自动为 PR 打标签（用于分类变更到对应 Release 板块）
    # 仅在官方仓库执行（避免 fork 仓库误触发）
    if: github.repository == 'LLiuHuan/arco-design-pro-vue'
    runs-on: ubuntu-latest # 运行环境：Ubuntu 最新版
    steps:
      # 步骤1：使用 release-drafter 工具自动生成/更新发布草稿
      - uses: release-drafter/release-drafter@v6 # 引用官方 release-drafter 动作
        env:
          # 内置令牌，用于授权操作 GitHub（创建 Release、读取 PR 信息等）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
