# 工作流名称，显示在 GitHub Actions 界面中
name: 'Close stale issues'

# 触发条件：定时执行
on:
  schedule:
    # cron 表达式，定义执行时间：每天凌晨 1 点（UTC 时间）
    - cron: '0 1 * * *'

jobs:
  # 定义一个名为 stale 的任务
  stale:
    # 条件：仅当当前仓库是 'LLiuHuan/arco-design-pro-vue' 时才运行
    if: github.repository == 'LLiuHuan/arco-design-pro-vue'
    # 运行环境：最新版 Ubuntu 系统
    runs-on: ubuntu-latest
    steps:
      # 使用官方的 stale 动作处理陈旧内容
      - uses: actions/stale@v9
        with:
          # 用于访问 GitHub API 的令牌
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # 给陈旧 issue 发送的提示消息
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days'
          # 翻译：此 issue 已过期，因为它已开放 60 天且无活动。移除 stale 标签或评论，否则将在 7 天内关闭
          
          # 给陈旧 PR 发送的提示消息
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days'
          # 翻译：此 PR 已过期，因为它已开放 60 天且无活动。移除 stale 标签或评论，否则将在 7 天内关闭
          
          # 不受过期规则影响的 issue 标签（带有这些标签的 issue 不会被标记为陈旧）
          exempt-issue-labels: 'bug,enhancement'
          # 说明：标记为 bug（bug 修复）和 enhancement（功能增强）的 issue 不会被自动处理
          
          # 多少天无活动后标记为陈旧
          days-before-stale: 60
          
          # 标记为陈旧后，多少天后自动关闭
          days-before-close: 7
